format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$character"""

[directory]
home_symbol = "~"
style = "yellow"
truncation_symbol = '…/'

[character]
success_symbol = "[➜ ](green)"
error_symbol = "[➜ ](red)"

[git_branch]
format = '\[[$branch]($style)\]'
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = '\[[$duration]($style)\] '