hide_window_decorations no
allow_remote_control yes
enabled_layouts splits
linux_display_server x11

background_opacity 0.92

cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

tab_bar_edge top
tab_bar_style powerline

map ctrl+x>2 launch --location=hsplit
map ctrl+x>3 launch --location=vsplit
map ctrl+x>0 close_window
map ctrl+x>1 close_other_windows_in_tab
map ctrl+x>o next_window
map alt+o next_window


# BEGIN_KITTY_THEME
# Adventure Time
include current-theme.conf
# END_KITTY_THEME